language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.5
      env: COVERAGE=1

services:
  - mongodb

before_script:
  - bash .travis/install.sh

script:
  - bash .travis/run.sh
